import { PhaseDefinition } from '../../../domain/world/phase-definition.model';

export const PHASE_REGISTRY: PhaseDefinition[] = [
  {
    id: 'phase-01',
    order: 1,
    title: 'Ruínas do Vale',
    biome: 'ruins',
    narrativeGoal: 'apresentar a queda do vale e iniciar a jornada de Kael',
    mainEnemyName: 'Errante de Cinza',
    visualSummary: 'casas destruídas, pontes quebradas, névoa baixa e postes apagados',
    mainMechanic: 'movimento básico, salto, ataque, coleta e leitura inicial de exploração',
    length: 'medium',
    difficulty: 1,
    worldWidth: 4700,
    segments: [
      { id: 'start', label: 'Entrada nas Ruínas', difficultyWeight: 1 },
      { id: 'middle', label: 'Pátio Quebrado', difficultyWeight: 1 },
      { id: 'pre-boss', label: 'Silêncio do Vale', difficultyWeight: 2 },
      { id: 'boss', label: 'Arena das Ruínas', difficultyWeight: 3 },
    ],
    boss: {
      bossId: 'boss-arauto-das-cinzas',
      bossName: 'Arauto das Cinzas',
      maxHp: 36,
      movementMode: 'jump-heavy',
      bossMusicId: 'phase-01-boss',
      dialog: {
        bossId: 'boss-arauto-das-cinzas',
        bossName: 'Arauto das Cinzas',
        lines: ['Ainda resta uma chama?', 'Então eu mesmo vou apagá-la.'],
        autoCloseMs: 2600,
      },
    },
    audio: {
      explorationMusicId: 'phase-01-exploration',
      bossMusicId: 'phase-01-boss',
      clearMusicId: 'phase-clear-theme',
    },
  },
  {
    id: 'phase-02',
    order: 2,
    title: 'Bosque das Lanternas Mortas',
    biome: 'dead-forest',
    narrativeGoal: 'mostrar a floresta seca e sombria tomada pela corrupção',
    mainEnemyName: 'Vigia Oco',
    visualSummary: 'raízes expostas, troncos ocos, árvores mortas e lanternas apagadas',
    mainMechanic: 'plataformas naturais, raízes, leitura vertical leve e saltos entre troncos',
    length: 'medium',
    difficulty: 2,
    worldWidth: 5200,
    segments: [
      { id: 'start', label: 'Raízes Secas', difficultyWeight: 1 },
      { id: 'middle', label: 'Troncos Ocos', difficultyWeight: 2 },
      { id: 'pre-boss', label: 'Luzes Mortas', difficultyWeight: 3 },
      { id: 'boss', label: 'Clareira Escura', difficultyWeight: 4 },
    ],
    boss: {
      bossId: 'boss-guardiao-do-bosque-morto',
      bossName: 'Guardião do Bosque Morto',
      maxHp: 44,
      movementMode: 'patrol',
      bossMusicId: 'phase-02-boss',
      dialog: {
        bossId: 'boss-guardiao-do-bosque-morto',
        bossName: 'Guardião do Bosque Morto',
        lines: ['Aqui nem a madeira respira.', 'Você também não vai respirar por muito tempo.'],
        autoCloseMs: 2600,
      },
    },
    audio: {
      explorationMusicId: 'phase-02-exploration',
      bossMusicId: 'phase-02-boss',
      clearMusicId: 'phase-clear-theme',
    },
  },
  {
    id: 'phase-03',
    order: 3,
    title: 'Cavernas do Eco Cinzento',
    biome: 'cave',
    narrativeGoal: 'levar Kael ao subterrâneo e aprofundar a sensação de ruína',
    mainEnemyName: 'Brasa Caída',
    visualSummary: 'pedras úmidas, precipícios, cristais quebrados, ecos e passagens estreitas',
    mainMechanic: 'saltos de precisão, descida vertical e leitura de espaços comprimidos',
    length: 'medium',
    difficulty: 3,
    worldWidth: 5600,
    segments: [
      { id: 'start', label: 'Entrada Rochosa', difficultyWeight: 2 },
      { id: 'middle', label: 'Eco Partido', difficultyWeight: 3 },
      { id: 'pre-boss', label: 'Fenda Profunda', difficultyWeight: 4 },
      { id: 'boss', label: 'Salão do Eco', difficultyWeight: 5 },
    ],
    boss: {
      bossId: 'boss-devorador-de-ecos',
      bossName: 'Devorador de Ecos',
      maxHp: 52,
      movementMode: 'jump-heavy',
      bossMusicId: 'phase-03-boss',
      dialog: {
        bossId: 'boss-devorador-de-ecos',
        bossName: 'Devorador de Ecos',
        lines: ['Toda voz aqui vira fome.', 'A sua será a próxima.'],
        autoCloseMs: 2600,
      },
    },
    audio: {
      explorationMusicId: 'phase-03-exploration',
      bossMusicId: 'phase-03-boss',
      clearMusicId: 'phase-clear-theme',
    },
  },
  {
    id: 'phase-04',
    order: 4,
    title: 'Rio das Memórias Afogadas',
    biome: 'river',
    narrativeGoal: 'introduzir a área de água parcial e a memória perdida do vale',
    mainEnemyName: 'Afogado de Cinza',
    visualSummary: 'trechos rasos, correnteza, plataformas escorregadias e partes submersas curtas',
    mainMechanic: 'controle de terreno molhado, fluxo de água e deslocamento parcial submerso',
    length: 'medium',
    difficulty: 4,
    worldWidth: 6000,
    segments: [
      { id: 'start', label: 'Margem Quebrada', difficultyWeight: 2 },
      { id: 'middle', label: 'Leito Afogado', difficultyWeight: 3 },
      { id: 'pre-boss', label: 'Reflexos Perdidos', difficultyWeight: 4 },
      { id: 'boss', label: 'Poço das Memórias', difficultyWeight: 5 },
    ],
    boss: {
      bossId: 'boss-serpe-afogada',
      bossName: 'Serpe Afogada',
      maxHp: 58,
      movementMode: 'patrol',
      bossMusicId: 'phase-04-boss',
      dialog: {
        bossId: 'boss-serpe-afogada',
        bossName: 'Serpe Afogada',
        lines: ['As memórias afundam aqui.', 'Você vai afundar com elas.'],
        autoCloseMs: 2600,
      },
    },
    audio: {
      explorationMusicId: 'phase-04-exploration',
      bossMusicId: 'phase-04-boss',
      clearMusicId: 'phase-clear-theme',
    },
  },
  {
    id: 'phase-05',
    order: 5,
    title: 'Pântano da Névoa Baixa',
    biome: 'swamp',
    narrativeGoal: 'passar pela parte mais lenta, pesada e doente do vale',
    mainEnemyName: 'Criatura do Lodo',
    visualSummary: 'lama, gás, troncos afundando e criaturas ocultas na névoa',
    mainMechanic: 'movimento mais lento, plataformas instáveis e leitura de perigo escondido',
    length: 'long',
    difficulty: 5,
    worldWidth: 7200,
    segments: [
      { id: 'start', label: 'Borda do Pântano', difficultyWeight: 3 },
      { id: 'middle', label: 'Névoa Baixa', difficultyWeight: 4 },
      { id: 'pre-boss', label: 'Lodo Profundo', difficultyWeight: 5 },
      { id: 'boss', label: 'Berço do Pântano', difficultyWeight: 6 },
    ],
    boss: {
      bossId: 'boss-mae-do-lodo',
      bossName: 'Mãe do Lodo',
      maxHp: 66,
      movementMode: 'jump-heavy',
      bossMusicId: 'phase-05-boss',
      dialog: {
        bossId: 'boss-mae-do-lodo',
        bossName: 'Mãe do Lodo',
        lines: ['Tudo aqui aprende a ceder.', 'Você também vai ceder.'],
        autoCloseMs: 2600,
      },
    },
    audio: {
      explorationMusicId: 'phase-05-exploration',
      bossMusicId: 'phase-05-boss',
      clearMusicId: 'phase-clear-theme',
    },
  },
  {
    id: 'phase-06',
    order: 6,
    title: 'Penhascos do Vento Pálido',
    biome: 'cliffs',
    narrativeGoal: 'mudar o ritmo para uma subida vertical mais aberta e perigosa',
    mainEnemyName: 'Corvo de Ferro',
    visualSummary: 'plataformas estreitas, vento empurrando, ruínas altas e sensação forte de queda',
    mainMechanic: 'subida vertical, leitura de altura e controle fino em áreas expostas',
    length: 'medium',
    difficulty: 6,
    worldWidth: 6200,
    segments: [
      { id: 'start', label: 'Escarpa Inicial', difficultyWeight: 3 },
      { id: 'middle', label: 'Correntes de Ar', difficultyWeight: 4 },
      { id: 'pre-boss', label: 'Borda dos Penhascos', difficultyWeight: 5 },
      { id: 'boss', label: 'Ninho do Vento', difficultyWeight: 6 },
    ],
    boss: {
      bossId: 'boss-corvo-palidao',
      bossName: 'Corvo do Vento Pálido',
      maxHp: 72,
      movementMode: 'patrol',
      bossMusicId: 'phase-06-boss',
      dialog: {
        bossId: 'boss-corvo-palidao',
        bossName: 'Corvo do Vento Pálido',
        lines: ['Subiu tanto só para cair melhor.', 'Eu cuido do resto.'],
        autoCloseMs: 2600,
      },
    },
    audio: {
      explorationMusicId: 'phase-06-exploration',
      bossMusicId: 'phase-06-boss',
      clearMusicId: 'phase-clear-theme',
    },
  },
  {
    id: 'phase-07',
    order: 7,
    title: 'Torres Quebradas de Ardan',
    biome: 'towers',
    narrativeGoal: 'introduzir as ruínas mecânicas do antigo castelo e sua vigilância corrompida',
    mainEnemyName: 'Vigia Corrompido',
    visualSummary: 'engrenagens antigas, corredores partidos, elevadores velhos e paredes rachadas',
    mainMechanic: 'movimento entre salões e trechos verticais curtos com máquinas antigas',
    length: 'medium',
    difficulty: 7,
    worldWidth: 6500,
    segments: [
      { id: 'start', label: 'Base da Torre', difficultyWeight: 4 },
      { id: 'middle', label: 'Corredores Partidos', difficultyWeight: 5 },
      { id: 'pre-boss', label: 'Engrenagens Mortas', difficultyWeight: 6 },
      { id: 'boss', label: 'Câmara Alta', difficultyWeight: 7 },
    ],
    boss: {
      bossId: 'boss-sentinela-de-ardan',
      bossName: 'Sentinela de Ardan',
      maxHp: 80,
      movementMode: 'static-corner',
      bossMusicId: 'phase-07-boss',
      dialog: {
        bossId: 'boss-sentinela-de-ardan',
        bossName: 'Sentinela de Ardan',
        lines: ['Ainda obedeço às ordens antigas.', 'E a ordem é matar intrusos.'],
        autoCloseMs: 2600,
      },
    },
    audio: {
      explorationMusicId: 'phase-07-exploration',
      bossMusicId: 'phase-07-boss',
      clearMusicId: 'phase-clear-theme',
    },
  },
  {
    id: 'phase-08',
    order: 8,
    title: 'Céu Partido',
    biome: 'sky',
    narrativeGoal: 'trazer a fase nas alturas com maior vazio, risco e tempestade',
    mainEnemyName: 'Espectro do Vento',
    visualSummary: 'pontes suspensas, ilhas flutuantes, tempestade escura e relâmpagos ao fundo',
    mainMechanic: 'saltos longos, leitura de vazio e controle em áreas muito abertas',
    length: 'medium',
    difficulty: 8,
    worldWidth: 6800,
    segments: [
      { id: 'start', label: 'Pontes no Vazio', difficultyWeight: 4 },
      { id: 'middle', label: 'Ilhas Partidas', difficultyWeight: 5 },
      { id: 'pre-boss', label: 'Tempestade Alta', difficultyWeight: 6 },
      { id: 'boss', label: 'Altar do Céu', difficultyWeight: 7 },
    ],
    boss: {
      bossId: 'boss-arconte-do-ceu-partido',
      bossName: 'Arconte do Céu Partido',
      maxHp: 88,
      movementMode: 'patrol',
      bossMusicId: 'phase-08-boss',
      dialog: {
        bossId: 'boss-arconte-do-ceu-partido',
        bossName: 'Arconte do Céu Partido',
        lines: ['Nem o céu te acolhe mais.', 'Eu só termino a queda.'],
        autoCloseMs: 2600,
      },
    },
    audio: {
      explorationMusicId: 'phase-08-exploration',
      bossMusicId: 'phase-08-boss',
      clearMusicId: 'phase-clear-theme',
    },
  },
  {
    id: 'phase-09',
    order: 9,
    title: 'Farol das Cinzas',
    biome: 'lighthouse',
    narrativeGoal: 'trazer a fase emocional ligada à família de Kael e à perda',
    mainEnemyName: 'Guardião Apagado',
    visualSummary: 'farol destruído, interior queimado, fogo apagado, memória e perda',
    mainMechanic: 'subida interna, corredores estreitos e leitura mais emocional do espaço',
    length: 'medium',
    difficulty: 9,
    worldWidth: 6900,
    segments: [
      { id: 'start', label: 'Base do Farol', difficultyWeight: 5 },
      { id: 'middle', label: 'Escadas Quebradas', difficultyWeight: 6 },
      { id: 'pre-boss', label: 'Salão da Memória', difficultyWeight: 7 },
      { id: 'boss', label: 'Coroa do Farol', difficultyWeight: 8 },
    ],
    boss: {
      bossId: 'boss-faroleiro-apagado',
      bossName: 'Faroleiro Apagado',
      maxHp: 96,
      movementMode: 'static-corner',
      bossMusicId: 'phase-09-boss',
      dialog: {
        bossId: 'boss-faroleiro-apagado',
        bossName: 'Faroleiro Apagado',
        lines: ['A chama já morreu faz tempo.', 'Você só chegou tarde demais.'],
        autoCloseMs: 2800,
      },
    },
    audio: {
      explorationMusicId: 'phase-09-exploration',
      bossMusicId: 'phase-09-boss',
      clearMusicId: 'phase-clear-theme',
    },
  },
  {
    id: 'phase-10',
    order: 10,
    title: 'Coração Enterrado',
    biome: 'buried-core',
    narrativeGoal: 'descer ao núcleo corrompido e orgânico do vale',
    mainEnemyName: 'Guardião Raiz',
    visualSummary: 'raízes petrificadas, energia corrompida e cenário opressor e vivo',
    mainMechanic: 'descida final, leitura de cenário orgânico e maior pressão de combate',
    length: 'long',
    difficulty: 10,
    worldWidth: 7800,
    segments: [
      { id: 'start', label: 'Entrada Profunda', difficultyWeight: 6 },
      { id: 'middle', label: 'Raízes Petrificadas', difficultyWeight: 7 },
      { id: 'pre-boss', label: 'Pulso Corrompido', difficultyWeight: 8 },
      { id: 'boss', label: 'Núcleo Enterrado', difficultyWeight: 9 },
    ],
    boss: {
      bossId: 'boss-nucleo-enterrado',
      bossName: 'Núcleo Enterrado',
      maxHp: 108,
      movementMode: 'jump-heavy',
      bossMusicId: 'phase-10-boss',
      dialog: {
        bossId: 'boss-nucleo-enterrado',
        bossName: 'Núcleo Enterrado',
        lines: ['Aqui o vale ainda pulsa.', 'Mas pulsa em dor.'],
        autoCloseMs: 2900,
      },
    },
    audio: {
      explorationMusicId: 'phase-10-exploration',
      bossMusicId: 'phase-10-boss',
      clearMusicId: 'phase-clear-theme',
    },
  },
  {
    id: 'phase-11',
    order: 11,
    title: 'Trono da Névoa',
    biome: 'fortress',
    narrativeGoal: 'preparar a reta final com clima de fim do mundo e silêncio pesado',
    mainEnemyName: 'Cavaleiro Nebuloso',
    visualSummary: 'fortaleza final, corredores frios, névoa densa e silêncio opressor',
    mainMechanic: 'combate duro, leitura curta e travessia tensa com pouco respiro',
    length: 'long',
    difficulty: 11,
    worldWidth: 8200,
    segments: [
      { id: 'start', label: 'Portão Final', difficultyWeight: 7 },
      { id: 'middle', label: 'Salões da Névoa', difficultyWeight: 8 },
      { id: 'pre-boss', label: 'Antecâmara do Trono', difficultyWeight: 9 },
      { id: 'boss', label: 'Trono Velado', difficultyWeight: 10 },
    ],
    boss: {
      bossId: 'boss-senhor-da-nevoa',
      bossName: 'Senhor da Névoa',
      maxHp: 120,
      movementMode: 'static-corner',
      bossMusicId: 'phase-11-boss',
      dialog: {
        bossId: 'boss-senhor-da-nevoa',
        bossName: 'Senhor da Névoa',
        lines: ['Você veio longe demais.', 'Agora vai ver o fim do vale.'],
        autoCloseMs: 3000,
      },
    },
    audio: {
      explorationMusicId: 'phase-11-exploration',
      bossMusicId: 'phase-11-boss',
      clearMusicId: 'phase-clear-theme',
    },
  },
  {
    id: 'phase-12',
    order: 12,
    title: 'Coração do Vale',
    biome: 'final-heart',
    narrativeGoal: 'encerrar a jornada com confronto final e restauração simbólica',
    mainEnemyName: 'Coração Corrompido',
    visualSummary: 'arena final curta, visual dramático, simbólico e de restauração',
    mainMechanic: 'confronto final com leitura limpa e grande peso dramático',
    length: 'medium',
    difficulty: 12,
    worldWidth: 9000,
    isFinalPhase: true,
    segments: [
      { id: 'start', label: 'Chegada ao Núcleo', difficultyWeight: 8 },
      { id: 'middle', label: 'Pulso do Vale', difficultyWeight: 9 },
      { id: 'pre-boss', label: 'Silêncio do Coração', difficultyWeight: 10 },
      { id: 'boss', label: 'Arena Final', difficultyWeight: 12 },
    ],
    boss: {
      bossId: 'boss-coracao-do-vale',
      bossName: 'Coração do Vale',
      maxHp: 180,
      movementMode: 'jump-heavy',
      bossMusicId: 'phase-12-boss',
      dialog: {
        bossId: 'boss-coracao-do-vale',
        bossName: 'Coração do Vale',
        lines: ['Se quer salvar este lugar...', 'Primeiro terá de sobreviver à sua dor.'],
        autoCloseMs: 3200,
      },
    },
    audio: {
      explorationMusicId: 'phase-12-exploration',
      bossMusicId: 'phase-12-boss',
      clearMusicId: 'true-ending-theme',
    },
  },
];

export function getPhaseDefinitionById(phaseId: string): PhaseDefinition {
  const phase = PHASE_REGISTRY.find((item: PhaseDefinition) => item.id === phaseId);

  if (!phase) {
    return PHASE_REGISTRY[0];
  }

  return phase;
}

export function getNextPhaseDefinition(
  currentPhaseId: string,
): PhaseDefinition | null {
  const currentIndex = PHASE_REGISTRY.findIndex(
    (item: PhaseDefinition) => item.id === currentPhaseId,
  );

  if (currentIndex === -1 || currentIndex === PHASE_REGISTRY.length - 1) {
    return null;
  }

  return PHASE_REGISTRY[currentIndex + 1];
}
