import { PhaseDefinition } from '../../domain/world/phase-definition.model';

export const PHASE_REGISTRY: PhaseDefinition[] = [
  {
    id: 'phase-01',
    order: 1,
    title: 'Ruínas do Vale',
    biome: 'ruins',
    narrativeGoal: 'mostrar a queda do vale e dar início à jornada de Kael',
    mainEnemyName: 'Errante de Cinza',
    visualSummary: 'casas destruídas, pontes quebradas, postes apagados, névoa baixa, árvores secas',
    mainMechanic: 'movimento, pulo, ataque, coleta de moedas e centelhas',
    length: 'medium',
    difficulty: 1,
    worldWidth: 4700,
    segments: [
      { id: 'start', label: 'Entrada nas Ruínas', difficultyWeight: 1 },
      { id: 'middle', label: 'Pátio Quebrado', difficultyWeight: 1 },
      { id: 'pre-boss', label: 'Silêncio de Cinza', difficultyWeight: 2 },
      { id: 'boss', label: 'Arena do Arauto', difficultyWeight: 3 },
    ],
    boss: {
      bossId: 'boss-arauto-das-cinzas',
      bossName: 'Arauto das Cinzas',
      maxHp: 36,
      movementMode: 'jump-heavy',
      bossMusicId: 'phase-01-boss',
      dialog: {
        bossId: 'boss-arauto-das-cinzas',
        bossName: 'Arauto das Cinzas',
        lines: ['Ainda resta uma chama?', 'Então eu mesmo vou soprá-la até morrer.'],
        autoCloseMs: 2600,
      },
    },
    audio: {
      explorationMusicId: 'phase-01-exploration',
      bossMusicId: 'phase-01-boss',
      clearMusicId: 'phase-clear-theme',
    },
  },
  {
    id: 'phase-02',
    order: 2,
    title: 'Bosque das Lanternas Mortas',
    biome: 'forest',
    narrativeGoal: 'mostrar que a corrupção tomou também os caminhos vivos do vale',
    mainEnemyName: 'Vigia Oco',
    visualSummary: 'floresta escura, galhos retorcidos, raízes expostas, lanternas antigas sem luz',
    mainMechanic: 'plataformas sobre troncos, raízes que atrapalham o caminho, trechos verticais curtos',
    length: 'medium',
    difficulty: 2,
    worldWidth: 5200,
    segments: [
      { id: 'start', label: 'Troncos Tombados', difficultyWeight: 1 },
      { id: 'middle', label: 'Raízes Expostas', difficultyWeight: 2 },
      { id: 'pre-boss', label: 'Lanternas Sem Luz', difficultyWeight: 3 },
      { id: 'boss', label: 'Clareira Corrompida', difficultyWeight: 4 },
    ],
    boss: {
      bossId: 'boss-guardiao-oco',
      bossName: 'Guardião Oco',
      maxHp: 44,
      movementMode: 'patrol',
      bossMusicId: 'phase-02-boss',
      dialog: {
        bossId: 'boss-guardiao-oco',
        bossName: 'Guardião Oco',
        lines: ['Você pisa onde a floresta morreu.', 'Agora vai apodrecer com ela.'],
        autoCloseMs: 2600,
      },
    },
    audio: {
      explorationMusicId: 'phase-02-exploration',
      bossMusicId: 'phase-02-boss',
      clearMusicId: 'phase-clear-theme',
    },
  },
  {
    id: 'phase-03',
    order: 3,
    title: 'Caverna do Eco Partido',
    biome: 'cave',
    narrativeGoal: 'Kael desce ao interior do vale e percebe que a corrupção vem de camadas mais profundas',
    mainEnemyName: 'Brasa Caída',
    visualSummary: 'rochas escuras, estalactites, cristais rachados, passagens estreitas, precipícios',
    mainMechanic: 'descida em profundidade, saltos precisos, teto baixo e sensação de claustrofobia',
    length: 'medium',
    difficulty: 3,
    worldWidth: 5600,
    segments: [
      { id: 'start', label: 'Entrada Rochosa', difficultyWeight: 2 },
      { id: 'middle', label: 'Cristais Partidos', difficultyWeight: 3 },
      { id: 'pre-boss', label: 'Eco Profundo', difficultyWeight: 4 },
      { id: 'boss', label: 'Fenda do Devorador', difficultyWeight: 5 },
    ],
    boss: {
      bossId: 'boss-devorador-de-ecos',
      bossName: 'Devorador de Ecos',
      maxHp: 52,
      movementMode: 'jump-heavy',
      bossMusicId: 'phase-03-boss',
      dialog: {
        bossId: 'boss-devorador-de-ecos',
        bossName: 'Devorador de Ecos',
        lines: ['Toda voz que caiu aqui virou fome.', 'A sua será a próxima.'],
        autoCloseMs: 2600,
      },
    },
    audio: {
      explorationMusicId: 'phase-03-exploration',
      bossMusicId: 'phase-03-boss',
      clearMusicId: 'phase-clear-theme',
    },
  },
  {
    id: 'phase-04',
    order: 4,
    title: 'Rio das Memórias Afogadas',
    biome: 'river',
    narrativeGoal: 'trazer uma fase mais emocional, com lembranças do passado do vale e pistas sobre quem Kael perdeu',
    mainEnemyName: 'Espíritos Afogados',
    visualSummary: 'ruínas parcialmente submersas, água escura, pontes partidas, reflexos frios',
    mainMechanic: 'correnteza, áreas molhadas, plataformas escorregadias e zonas rasas',
    length: 'medium',
    difficulty: 4,
    worldWidth: 6000,
    segments: [
      { id: 'start', label: 'Margem Afogada', difficultyWeight: 2 },
      { id: 'middle', label: 'Pilares Submersos', difficultyWeight: 3 },
      { id: 'pre-boss', label: 'Reflexo Partido', difficultyWeight: 4 },
      { id: 'boss', label: 'Leito Frio', difficultyWeight: 5 },
    ],
    boss: {
      bossId: 'boss-serpe-do-leito-frio',
      bossName: 'Serpe do Leito Frio',
      maxHp: 58,
      movementMode: 'patrol',
      bossMusicId: 'phase-04-boss',
      dialog: {
        bossId: 'boss-serpe-do-leito-frio',
        bossName: 'Serpe do Leito Frio',
        lines: ['As memórias afundam aqui.', 'E você vai afundar com elas.'],
        autoCloseMs: 2600,
      },
    },
    audio: {
      explorationMusicId: 'phase-04-exploration',
      bossMusicId: 'phase-04-boss',
      clearMusicId: 'phase-clear-theme',
    },
  },
  {
    id: 'phase-05',
    order: 5,
    title: 'Pântano da Névoa Baixa',
    biome: 'swamp',
    narrativeGoal: 'passar pela parte mais sufocante e doente do vale',
    mainEnemyName: 'Criaturas de Lodo e Ferrugem',
    visualSummary: 'lama escura, troncos caídos, gás subindo do chão, vegetação morta',
    mainMechanic: 'movimento pesado, plataformas que afundam, saltos curtos com timing',
    length: 'long',
    difficulty: 5,
    worldWidth: 7200,
    segments: [
      { id: 'start', label: 'Borda do Pântano', difficultyWeight: 3 },
      { id: 'middle', label: 'Névoa Rasteira', difficultyWeight: 4 },
      { id: 'pre-boss', label: 'Lodo Profundo', difficultyWeight: 5 },
      { id: 'boss', label: 'Berço Cinzento', difficultyWeight: 6 },
    ],
    boss: {
      bossId: 'boss-mae-do-lodo-cinzento',
      bossName: 'Mãe do Lodo Cinzento',
      maxHp: 66,
      movementMode: 'jump-heavy',
      bossMusicId: 'phase-05-boss',
      dialog: {
        bossId: 'boss-mae-do-lodo-cinzento',
        bossName: 'Mãe do Lodo Cinzento',
        lines: ['Tudo o que entra no lodo aprende a ceder.', 'Você também vai.'],
        autoCloseMs: 2600,
      },
    },
    audio: {
      explorationMusicId: 'phase-05-exploration',
      bossMusicId: 'phase-05-boss',
      clearMusicId: 'phase-clear-theme',
    },
  },
  {
    id: 'phase-06',
    order: 6,
    title: 'Penhascos do Vento Pálido',
    biome: 'cliffs',
    narrativeGoal: 'mudar o ritmo para sensação de ascensão e superação',
    mainEnemyName: 'Corvos de Ferro',
    visualSummary: 'paredões altos, ruínas nas bordas, abismos, céu aberto cinzento',
    mainMechanic: 'subida vertical, vento empurrando, plataformas estreitas e uso maior do dash',
    length: 'medium',
    difficulty: 6,
    worldWidth: 6200,
    segments: [
      { id: 'start', label: 'Parede Externa', difficultyWeight: 3 },
      { id: 'middle', label: 'Correntes de Ar', difficultyWeight: 4 },
      { id: 'pre-boss', label: 'Borda dos Abismos', difficultyWeight: 5 },
      { id: 'boss', label: 'Ninho de Ferro', difficultyWeight: 6 },
    ],
    boss: {
      bossId: 'boss-corvo-de-ferro',
      bossName: 'Corvo de Ferro',
      maxHp: 72,
      movementMode: 'patrol',
      bossMusicId: 'phase-06-boss',
      dialog: {
        bossId: 'boss-corvo-de-ferro',
        bossName: 'Corvo de Ferro',
        lines: ['Subiu tanto para cair melhor.', 'Vou te abrir no céu.'],
        autoCloseMs: 2600,
      },
    },
    audio: {
      explorationMusicId: 'phase-06-exploration',
      bossMusicId: 'phase-06-boss',
      clearMusicId: 'phase-clear-theme',
    },
  },
  {
    id: 'phase-07',
    order: 7,
    title: 'Torres Quebradas de Ardan',
    biome: 'towers',
    narrativeGoal: 'aproximar Kael do antigo centro de defesa e poder do vale',
    mainEnemyName: 'Sentinelas Corrompidas',
    visualSummary: 'torres rachadas, engrenagens antigas, passarelas suspensas, mecanismos velhos',
    mainMechanic: 'elevadores, plataformas móveis, corredores estreitos e combate fechado',
    length: 'medium',
    difficulty: 7,
    worldWidth: 6500,
    segments: [
      { id: 'start', label: 'Passarelas Partidas', difficultyWeight: 4 },
      { id: 'middle', label: 'Salões Mecânicos', difficultyWeight: 5 },
      { id: 'pre-boss', label: 'Engrenagens Mortas', difficultyWeight: 6 },
      { id: 'boss', label: 'Câmara Estilhaçada', difficultyWeight: 7 },
    ],
    boss: {
      bossId: 'boss-sentinela-estilhacada',
      bossName: 'Sentinela Estilhaçada',
      maxHp: 80,
      movementMode: 'static-corner',
      bossMusicId: 'phase-07-boss',
      dialog: {
        bossId: 'boss-sentinela-estilhacada',
        bossName: 'Sentinela Estilhaçada',
        lines: ['Ainda obedeço.', 'E minha ordem é rasgar intrusos.'],
        autoCloseMs: 2600,
      },
    },
    audio: {
      explorationMusicId: 'phase-07-exploration',
      bossMusicId: 'phase-07-boss',
      clearMusicId: 'phase-clear-theme',
    },
  },
  {
    id: 'phase-08',
    order: 8,
    title: 'Céu Partido',
    biome: 'sky',
    narrativeGoal: 'dar ao jogo um momento mais épico e grandioso antes da reta emocional final',
    mainEnemyName: 'Espectros do Vento',
    visualSummary: 'pontes suspensas, ilhas quebradas no ar, tempestade ao fundo, relâmpagos distantes',
    mainMechanic: 'saltos longos, risco de queda, inimigos aéreos e vento forte',
    length: 'medium',
    difficulty: 8,
    worldWidth: 6800,
    segments: [
      { id: 'start', label: 'Pontes no Vazio', difficultyWeight: 4 },
      { id: 'middle', label: 'Ilhas Partidas', difficultyWeight: 5 },
      { id: 'pre-boss', label: 'Coroa das Nuvens', difficultyWeight: 6 },
      { id: 'boss', label: 'Altar da Tempestade', difficultyWeight: 7 },
    ],
    boss: {
      bossId: 'boss-arconte-da-tempestade-cinza',
      bossName: 'Arconte da Tempestade Cinza',
      maxHp: 88,
      movementMode: 'patrol',
      bossMusicId: 'phase-08-boss',
      dialog: {
        bossId: 'boss-arconte-da-tempestade-cinza',
        bossName: 'Arconte da Tempestade Cinza',
        lines: ['Nem o céu te aceita mais.', 'Eu só vou terminar o trabalho.'],
        autoCloseMs: 2600,
      },
    },
    audio: {
      explorationMusicId: 'phase-08-exploration',
      bossMusicId: 'phase-08-boss',
      clearMusicId: 'phase-clear-theme',
    },
  },
  {
    id: 'phase-09',
    order: 9,
    title: 'Cripta das Chamas Mudas',
    biome: 'crypt',
    narrativeGoal: 'mostrar a corrupção espiritual do vale',
    mainEnemyName: 'Monges da Cinza',
    visualSummary: 'criptas abertas, brasas sem calor, corredores de pedra negra, velas apagadas',
    mainMechanic: 'corredores estreitos, armadilhas de chão e fogo residual intermitente',
    length: 'medium',
    difficulty: 9,
    worldWidth: 6900,
    segments: [
      { id: 'start', label: 'Corredor Funéreo', difficultyWeight: 5 },
      { id: 'middle', label: 'Naves Mortas', difficultyWeight: 6 },
      { id: 'pre-boss', label: 'Círio Apagado', difficultyWeight: 7 },
      { id: 'boss', label: 'Abóbada da Cinza', difficultyWeight: 8 },
    ],
    boss: {
      bossId: 'boss-abade-do-cirio-morto',
      bossName: 'Abade do Círio Morto',
      maxHp: 96,
      movementMode: 'static-corner',
      bossMusicId: 'phase-09-boss',
      dialog: {
        bossId: 'boss-abade-do-cirio-morto',
        bossName: 'Abade do Círio Morto',
        lines: ['Você ainda carrega luz?', 'Então vou apagar sua alma com minhas próprias mãos.'],
        autoCloseMs: 2800,
      },
    },
    audio: {
      explorationMusicId: 'phase-09-exploration',
      bossMusicId: 'phase-09-boss',
      clearMusicId: 'phase-clear-theme',
    },
  },
  {
    id: 'phase-10',
    order: 10,
    title: 'Cidadela do Ferro Frio',
    biome: 'citadel',
    narrativeGoal: 'mostrar o vale como máquina de opressão já completamente desfigurada',
    mainEnemyName: 'Operários Corrompidos',
    visualSummary: 'fortaleza industrial caída, correntes, portões, aço enegrecido, fumaça densa',
    mainMechanic: 'plataformas móveis pesadas, prensas, elevadores e combate em corredores industriais',
    length: 'long',
    difficulty: 10,
    worldWidth: 7800,
    segments: [
      { id: 'start', label: 'Portão de Ferro', difficultyWeight: 6 },
      { id: 'middle', label: 'Forjas Mortas', difficultyWeight: 7 },
      { id: 'pre-boss', label: 'Galeria de Correntes', difficultyWeight: 8 },
      { id: 'boss', label: 'Câmara do Carcereiro', difficultyWeight: 9 },
    ],
    boss: {
      bossId: 'boss-carcereiro-de-aco',
      bossName: 'Carcereiro de Aço',
      maxHp: 108,
      movementMode: 'jump-heavy',
      bossMusicId: 'phase-10-boss',
      dialog: {
        bossId: 'boss-carcereiro-de-aco',
        bossName: 'Carcereiro de Aço',
        lines: ['Aqui até o ferro aprende a obedecer.', 'E você vai gritar como todos os outros.'],
        autoCloseMs: 2900,
      },
    },
    audio: {
      explorationMusicId: 'phase-10-exploration',
      bossMusicId: 'phase-10-boss',
      clearMusicId: 'phase-clear-theme',
    },
  },
  {
    id: 'phase-11',
    order: 11,
    title: 'Jardins do Coração Morto',
    biome: 'garden',
    narrativeGoal: 'ligar Kael às perdas do vale antes da reta final',
    mainEnemyName: 'Noivas de Vidro',
    visualSummary: 'jardins arruinados, estátuas partidas, flores secas, espelhos rachados, chuva fina',
    mainMechanic: 'plataformas delicadas, caminhos falsos, leitura visual emocional',
    length: 'medium',
    difficulty: 11,
    worldWidth: 7000,
    segments: [
      { id: 'start', label: 'Alameda Quebrada', difficultyWeight: 6 },
      { id: 'middle', label: 'Espelhos Rachados', difficultyWeight: 7 },
      { id: 'pre-boss', label: 'Rosas Sem Sangue', difficultyWeight: 8 },
      { id: 'boss', label: 'Pavilhão da Rosa Negra', difficultyWeight: 9 },
    ],
    boss: {
      bossId: 'boss-dama-da-rosa-negra',
      bossName: 'Dama da Rosa Negra',
      maxHp: 116,
      movementMode: 'patrol',
      bossMusicId: 'phase-11-boss',
      dialog: {
        bossId: 'boss-dama-da-rosa-negra',
        bossName: 'Dama da Rosa Negra',
        lines: ['Você chegou tarde demais.', 'Tudo o que amava já apodreceu sem você.'],
        autoCloseMs: 2900,
      },
    },
    audio: {
      explorationMusicId: 'phase-11-exploration',
      bossMusicId: 'phase-11-boss',
      clearMusicId: 'phase-clear-theme',
    },
  },
  {
    id: 'phase-12',
    order: 12,
    title: 'Trono das Cinzas Vivas',
    biome: 'throne',
    narrativeGoal: 'preparar a verdade final e destruir a ideia de que derrotar um único senhor salvaria o vale',
    mainEnemyName: 'Cavaleiros da Cinza Viva',
    visualSummary: 'salões destruídos, brasas eternas, tronos quebrados, tapeçarias queimadas',
    mainMechanic: 'combate duro, elites, leitura rápida, menos respiro',
    length: 'long',
    difficulty: 12,
    worldWidth: 8200,
    segments: [
      { id: 'start', label: 'Salão Carbonizado', difficultyWeight: 7 },
      { id: 'middle', label: 'Marcha da Coroa Oca', difficultyWeight: 8 },
      { id: 'pre-boss', label: 'Antecâmara Rubra', difficultyWeight: 9 },
      { id: 'boss', label: 'Trono das Cinzas', difficultyWeight: 10 },
    ],
    boss: {
      bossId: 'boss-rei-sem-chama',
      bossName: 'Rei Sem Chama',
      maxHp: 132,
      movementMode: 'static-corner',
      bossMusicId: 'phase-12-boss',
      dialog: {
        bossId: 'boss-rei-sem-chama',
        bossName: 'Rei Sem Chama',
        lines: ['Eu vi reis se ajoelharem diante das cinzas.', 'O que faz você pensar que é diferente?'],
        autoCloseMs: 3000,
      },
    },
    audio: {
      explorationMusicId: 'phase-12-exploration',
      bossMusicId: 'phase-12-boss',
      clearMusicId: 'phase-clear-theme',
    },
  },
  {
    id: 'final-phase',
    order: 13,
    title: 'Vale do Acesso',
    biome: 'liminal',
    narrativeGoal: 'encerrar a jornada com um lugar mágico, quebrado e sagrado ao mesmo tempo',
    mainEnemyName: 'Guardiões do Umbral',
    visualSummary: 'montanhas distantes, brilho dourado ferido, ruínas suspensas, raízes de luz e cinza',
    mainMechanic: 'caminhada silenciosa, transição narrativa, boss duplo e ápice da dificuldade',
    length: 'long',
    difficulty: 14,
    worldWidth: 9000,
    isFinalPhase: true,
    segments: [
      { id: 'start', label: 'Passagem do Umbral', difficultyWeight: 8 },
      { id: 'middle', label: 'Raízes da Luz Ferida', difficultyWeight: 9 },
      { id: 'pre-boss', label: 'Cume do Acesso', difficultyWeight: 10 },
      { id: 'boss', label: 'Coração Cindido', difficultyWeight: 12 },
    ],
    boss: {
      bossId: 'boss-coracao-cindido-de-lumen',
      bossName: 'Coração Cindido de Lumen',
      maxHp: 220,
      movementMode: 'jump-heavy',
      bossMusicId: 'final-phase-boss-2',
      dialog: {
        bossId: 'boss-coracao-cindido-de-lumen',
        bossName: 'Coração Cindido de Lumen',
        lines: ['Eu fui a luz deste vale.', 'Agora serei a sua última noite.'],
        autoCloseMs: 3200,
      },
    },
    audio: {
      explorationMusicId: 'final-phase-exploration',
      bossMusicId: 'final-phase-boss-2',
      clearMusicId: 'true-ending-theme',
    },
  },
];

export function getPhaseDefinitionById(phaseId: string): PhaseDefinition {
  const phase = PHASE_REGISTRY.find((item) => item.id === phaseId);

  if (!phase) {
    return PHASE_REGISTRY[0];
  }

  return phase;
}

export function getNextPhaseDefinition(currentPhaseId: string): PhaseDefinition | null {
  const currentIndex = PHASE_REGISTRY.findIndex((item) => item.id === currentPhaseId);

  if (currentIndex === -1 || currentIndex === PHASE_REGISTRY.length - 1) {
    return null;
  }

  return PHASE_REGISTRY[currentIndex + 1];
}
